### ISSUE TITLE
ModuleNotFoundError: No module named 'agents'

### ISSUE THREAD

**Issue by Jenny12388** [CollaborativePerception/V2Xverse#32]
When I run
bash ./simulation/data_collection/scripts/weather-0/routes_town01_0.sh

There's error of 
simulation/leaderboard/leaderboard/leaderboard_evaluator_parameter.py:24: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
Traceback (most recent call last):
  File "simulation/leaderboard/leaderboard/leaderboard_evaluator_parameter.py", line 42, in <module>
    from leaderboard.scenarios.scenario_manager import ScenarioManager
  File "/home/jenny/Documents/V2Xverse/simulation/leaderboard/leaderboard/scenarios/scenario_manager.py", line 25, in <module>
    from leaderboard.autoagents.agent_wrapper import AgentWrapper, AgentError
  File "/home/jenny/Documents/V2Xverse/simulation/leaderboard/leaderboard/autoagents/agent_wrapper.py", line 21, in <module>
    from leaderboard.autoagents.autonomous_agent import Track
  File "/home/jenny/Documents/V2Xverse/simulation/leaderboard/leaderboard/autoagents/autonomous_agent.py", line 17, in <module>
    from leaderboard.utils.route_manipulation import downsample_route
  File "/home/jenny/Documents/V2Xverse/simulation/leaderboard/leaderboard/utils/route_manipulation.py", line 16, in <module>
    from agents.navigation.global_route_planner import GlobalRoutePlanner
ModuleNotFoundError: No module named 'agents'

Can I have the agent file, please? or anyone know how to solve this issue?

**Comment by gjliu9** [comment]
I'm sorry for not getting back to you sooner! This issue is likely due to the absence of the proper CARLA environment variable. Make sure to set 'export CARLA_ROOT=external_paths/carla_root' in the shell script and link external_paths/carla_root to your CARLA path.
